### ISSUE TITLE
Issue: Code embed does not allow special characters ��

### ISSUE THREAD

**Issue by fonsecagabriella** [trigaten/Learn_Prompting#1006]
Certain special characters such as ã, é, etc, which are essential in some languages, are not displayed correctly in the code embedding.  ���

Example here: https://learnprompting.org/pt/docs/basic_applications/writing_emails

**Comment by trigaten** [comment]
Could you try rewriting them? I believe I fixed this issue.

**Comment by trigaten** [comment]
Verified that this is solved.
