### ISSUE TITLE
gpt-4 model id is not found error

### ISSUE THREAD

**Issue by myvocabu** [trigaten/Learn_Prompting#1008]
Hello, looks like you are requesting gpt-4 model regardless it's not present in the model list returned by the endpoint: https://api.openai.com/v1/models

All the requests to https://api.openai.com/v1/models/gpt-4 are failing with 404 
{
  "error": {
    "message": "The model 'gpt-4' does not exist",
    "type": "invalid_request_error",
    "param": "model",
    "code": "model_not_found"
  }
}

maybe the id is been changed. At least on the screen, there is 'text-davinci-003'

**Comment by trigaten** [comment]
It seems you don't have access to gpt-4, have you joined the waitlist? I opened an issue on this here: https://github.com/PromptLabs/embed.learnprompting.org/issues/6

**Comment by myvocabu** [comment]
Hello,
Please make sure users can chose another model, otherwise ‘embeds’ have no sense for wide auditory. Even better it that is happening seamlessly, with pre-flight request to check what models are available for account and chose by priority.
Regards

**Comment by trigaten** [comment]
I made an issue about other models: https://github.com/PromptLabs/embed.learnprompting.org/issues/7

I don't currently have time to do this, but if you are interested please submit a PR!
