### ISSUE TITLE
My OPEN AI API Key is not working in the Embeds

### ISSUE THREAD

**Issue by pravyn25c** [trigaten/Learn_Prompting#1013]
**Sorry, what can I clarify?**
[](url)
![Screenshot 2023-07-22 185758](https://github.com/trigaten/Learn_Prompting/assets/56546289/0847086d-fbf4-42de-b773-2236e455fada)

**Comment by trigaten** [comment]
Try another key!

If it still doesn't work, please send a screenshot of the browser console.
