### ISSUE TITLE
Increase tokes for embeds

### ISSUE THREAD

**Issue by fonsecagabriella** [trigaten/Learn_Prompting#1028]
For embeds with more extended instructions, the output is being cropped.
It happens with most examples in the /intermediate section ie.

<img width="941" alt="Screenshot 2023-07-25 at 09 28 31" src="https://github.com/trigaten/Learn_Prompting/assets/1550446/80e81026-a998-44d8-8b71-ee6a58a198b7">

**Comment by trigaten** [comment]
Yep!
