### ISSUE TITLE
Mentioned Prompt for multiplication did not worked in ChatGPT

### ISSUE THREAD

**Issue by shivam-maurya-git** [trigaten/Learn_Prompting#1062]
On [this page](https://learnprompting.org/docs/basics/prompt_engineering)  at Prompt Engineering Course, there is a second method mentioned about getting correct result of a multiplication but it did not worked. Given answer is wrong.
![image](https://github.com/trigaten/Learn_Prompting/assets/74864959/4e486647-5149-4498-9524-d61a79abeec7)

**Comment by trigaten** [comment]
Unfortunately, chatgpt is non-deterministic, so this sometimes happens. I am updating the page to note this.

**Comment by shivam-maurya-git** [comment]
@trigaten . Thanks I will also note that while reading further at learnprompt.org

**Comment by trigaten** [comment]
Please read learnprompting.org

learnprompt.org appears to be a scam site :)

**Comment by shivam-maurya-git** [comment]
> @trigaten . Thanks I will also note that while reading further at learnprompt.org

Yes, learnprompting.org , I am on it, I just written it in short, sorry for inconvenience.
