### ISSUE TITLE
Website Feature of Article Rating System

### ISSUE THREAD

**Issue by macasas** [trigaten/Learn_Prompting#1094]
-1 for current article rating system which only uses colours, 2 of which are identical to 25% of the population who are colourblind, and then using those coloured icons to explain something, made even harder by the use of gradients.  

[article-rating-system](https://learnprompting.org/docs/intro#article-rating-system)

GPT and prompting is primarily a text-based environment where people like me can thrive, because there is no requirement to see and differentiate between colours, but you have made it a colour based learning resource.

Please consider becoming a more inclusive learning environment, which you could do by simply giving the existing icons a letter reference, and using larger, solid colours that do not match colourblind patterns of similarity.  So it would be as easy as adding 1,2,3,4 to your icons.

Thanks

**Comment by trigaten** [comment]
Done!
