### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by allelive** [trigaten/Learn_Prompting#1115]
**Sorry, what can I clarify?**
git clone https://github.com/trigaten/Learn_Prompting.git
Clone in 'Learn_Prompting' in corso...
remote: Enumerating objects: 661790, done.
remote: Counting objects: 100% (68159/68159), done.
remote: Compressing objects: 100% (8881/8881), done.
error: RPC non riuscita; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
fatal: l'interlocutore remoto ha chiuso inaspettatamente la connessione
fatal: EOF prematuro
fatal: index-pack non riuscito
ale@ale-Lenovo-B50-80 ~ [128]>

**Comment by trigaten** [comment]
It seems you lost connection, reclone.
