### ISSUE TITLE
Typo https://github.com/trigaten/Learn_Prompting/blob/v0.0.2/docs/IDEs/promptsai.md

### ISSUE THREAD

**Issue by pleabargain** [trigaten/Learn_Prompting#112]
**Sorry, where's the typo?**

https://learnprompting.org/docs/IDEs/promptsai

[Prompts.ai](https://prompts.ai/) provides a playground similar to the GPT-3 Playground, but with some added features. It is no lonnger being developed.

lonnger

curiously the source file doesn't have this phrase
![image](https://user-images.githubusercontent.com/640846/208683478-4ef5e243-cae6-47b3-99e6-2d5b2d7f778e.png)

**Comment by trigaten** [comment]
Thanks, just fixed it!
