### ISSUE TITLE
Documentation Link Not Found (404 Error)

### ISSUE THREAD

**Issue by devBarcode** [trigaten/Learn_Prompting#1132]
Clicking the "DOCS" button on the homepage redirects users to a page that doesn't exist: "https://learnprompting.org/it/docs/intro". This occurs even when changing the language code from "it" to "en" (https://learnprompting.org/en/docs/intro).

While other language translations work correctly (e.g., https://learnprompting.org/fr/docs/intro), the English documentation link seems broken.

**Comment by trigaten** [comment]
Hello @devBarcode, this is pretty concerning. English translations are stored at `https://learnprompting.org/docs/intro`. Can you send a video/screenshots showing what happens or you when you click the button? I can't reproduce this on Safari.

**Comment by devBarcode** [comment]
Sure @trigaten, I have tested this issue in Firefox and confirmed the behavior.
Video: https://www.youtube.com/watch?v=3FqSAWNzNrM

**Comment by trigaten** [comment]
That is super helpful, are you in Italy?

**Comment by devBarcode** [comment]
Yes I'm based in Italy

**Comment by trigaten** [comment]
Gotcha, we are looking into this now!

**Comment by trigaten** [comment]
@devBarcode if you go to https://learnprompting.org, then click docs, does it work?

**Comment by trigaten** [comment]
Unfortunately, we don't have an Italian translation yet.

**Comment by devBarcode** [comment]
> @devBarcode if you go to https://learnprompting.org, then click docs, does it work (that is, not go to 404)?

Oh yes! It works now correctly, thank you! 
p.s. Don't worry for the Italian translation, at least for me, english is quite easy to read and understand.
