### ISSUE TITLE
STRUDEL: Structured Dialogue Summarization for Dialogue Comprehension

### ISSUE THREAD

**Issue by trigaten** [trigaten/Learn_Prompting#175]

**Comment by louisfb01** [comment]
Linking the paper here for convenience, https://arxiv.org/pdf/2212.12652.pdf

**Comment by Nitesh053** [comment]
@trigaten 
Have summarised this in a good doc. Can you please review and let me know on the level of detailing.
[STRUDEL](https://docs.google.com/document/d/1vuzLTOFh59NY32wAJulQWWQkYcQHsp1D/edit?usp=sharing&ouid=117128287139437739920&rtpof=true&sd=true)

**Comment by trigaten** [comment]
> @trigaten Have summarised this in a good doc. Can you please review and let me know on the level of detailing. [STRUDEL](https://docs.google.com/document/d/1vuzLTOFh59NY32wAJulQWWQkYcQHsp1D/edit?usp=sharing&ouid=117128287139437739920&rtpof=true&sd=true)

Wow there is a lot of detail in there! At first glance, this is highly technical, so the embeddings info is likely too much for readers. The eventual page(s) should focus on the prompting aspect.

**Comment by trigaten** [comment]
I only see the word prompt a few times in the doc. Following https://learnprompting.org/contribute#adding-papers, it may not make sense to include it as its own page. I will have to look more later.

**Comment by trigaten** [comment]
@Nitesh053 I just went thru the paper and I don't think it is a good fit for an article since is not about prompting. IMO this would be a good paper to add to the bib as smtg interesting and prompting related. What do you think?

**Comment by Nitesh053** [comment]
@trigaten Yes paper has lot of technical details and prompting is only used to generate structured Dialogue. It's small use case of prompting.

**Comment by trigaten** [comment]
@Nitesh053 cool, maybe take a look at the ATLAS and LAMBADA papers in other open issues. It would be to know if these contain useful prompting tips.
