### ISSUE TITLE
Edit this page - links are broken

### ISSUE THREAD

**Issue by thepok** [trigaten/Learn_Prompting#199]
Tried it on langchain page - leads to 404

**Comment by trigaten** [comment]
What link? The one on this page: https://learnprompting.org/docs/tooling/IDEs/langchain ?

If you are referring to the GitHub one, it works for me.

**Comment by thepok** [comment]
yeah at the link you provided at the bottom left. If i click it i get to

[Edit this page](https://github.com/trigaten/promptgineering/tree/v0.0.2/docs/tooling/IDEs/langchain.md)

and its not working.

**Comment by trigaten** [comment]
I found the problem.
