### ISSUE TITLE
Clarification - LLM?

### ISSUE THREAD

**Issue by pfmmercier** [trigaten/Learn_Prompting#206]
**Sorry, what can I clarify?**
On this page: https://learnprompting.org/docs/intro
You use an acronym I'm not familiar with: "LLM" - see: "Reliability: How to make LLMs more reliable"
I did a Google search for it and it references some sort of "Legal" meaning to is (which I'm guessing is not what you're referring to).

Many thanks and many thanks for creating the learning material.

Patrick

**Comment by pfmmercier** [comment]
Ah... just spotted your vocabulary page: https://learnprompting.org/docs/vocabulary.
"Large Language Models" rathern than "Latin Legum Magister".
Thanks.

**Comment by trigaten** [comment]
We are working on having the definitions pop up wherever u see the words :)
