### ISSUE TITLE
ChatGPT page

### ISSUE THREAD

**Issue by louisfb01** [trigaten/Learn_Prompting#220]
A dedicated page on ChatGPT with tips and tricks to use it + a small intro of what it is.

Assigning myself and Nitesh.

Myself: what is chatgpt + do the PR
Nitesh: please update here with a list of tips and tricks for chatgpt with examples. Look into twitter and blogs as I sent you.

**Comment by Nitesh053** [comment]
@louisfb01 - Attached doc talk about How to use chatGPT for UI/UX design 

https://docs.google.com/document/d/1wDGD6bGCrXEYa1UIk5LSmVILR_22R18T/edit?usp=sharing&ouid=117128287139437739920&rtpof=true&sd=true

**Comment by Nitesh053** [comment]
@louisfb01 Found few on twitter, let me know if this helps

https://docs.google.com/document/d/14-3JEUrjn5XvmbF8K8NWhATD2DTyKNmY/edit?usp=sharing&ouid=117128287139437739920&rtpof=true&sd=true

**Comment by Nitesh053** [comment]
@louisfb01 Added examples from the PPT you shared. I have not covered the whole ppt yet i will keep adding to this doc. Just the work completed till now.

https://docs.google.com/document/d/1rZnjLYmUNCqFHat6jDE59RPI8c4y67kj/edit?usp=sharing&ouid=117128287139437739920&rtpof=true&sd=true

**Comment by dr-nefardio3058** [comment]
Is this solved? If it is, @louisfb01 ,please close this issue as it has been adressed.

**Comment by dr-nefardio3058** [comment]
Hi there, @louisfb01 ! We wanted to check in and see if the issue you reported earlier has been resolved. If it has, we would greatly appreciate it if you could take a moment to close the issue. It's super easy – just click the "Close Issue" button at the bottom of the issue page.

Keeping the issue tracker clean and tidy is important for the health of our codebase. With fewer issues to manage, we can focus on the ones that need our attention and ensure that our code remains maintainable in the long run. For example, it's easier to identify trends and common issues when there are fewer open issues, which can lead to more efficient bug fixing and better overall code quality.

Thanks so much for your help in keeping our repo organized and contributing! 😄
