### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Rishikesh0811** [trigaten/Learn_Prompting#221]
Hi Trigaten,

Thanks for making such a wonderful course. 

The course has been understandable so far even with zero prior knowldege on prompting. But now I am facing problem in understandig a section _**[What's in a Prompt?](https://learnprompting.org/docs/intermediate/whats_in_a_prompt)**_

For example, In Ground Truth Matters Little, the example given needs some explanation for starter like us :) 
The Labelspace also needs some explanation as there was no mention of it before.
In format matters section some example will be of great use.

The changes I am asking to make is to help beginners like me to get started with this amazing tech. 
I must reiterate, you have done a fabulous job of putting this course together.

Many Thanks
Rishikesh

**Comment by trigaten** [comment]
Thanks for making the issue! Check out the vocabulary page for label space. I will look into clarifying this, and I am happy to accept a PR if you want to make one!

**Comment by trigaten** [comment]
I refined the page and added an example. Let me know what you think!
