### ISSUE TITLE
https://learnprompting.org/docs/basics/promptingTypo

### ISSUE THREAD

**Issue by dtsoden** [trigaten/Learn_Prompting#234]
Prompt Engineering
If, instead of asking What is 100*100?, we ask What is 100*100? Make sure your answer has the correct number of 0s:, GPT-3 will answer 10,000 (correct).

Nothing changes you say "What is 100*100?" both times, thus implying something was asked differently. Perhaps I am missing something?

**Comment by trigaten** [comment]
You are not missing anything. In the past GPT-3 would make this mistake, but it appears to have been updated.

**Comment by trigaten** [comment]
Thanks for opening the issue, I will get on generating a better example.
