### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mrboombooms** [trigaten/Learn_Prompting#240]
**Sorry, where's the typo?**
love the website, in role prompting, the calculations dont add up? worth noting! I could be wrong im no AI but when I put the same calc in my ai i got two different responses and then used my calculator to confirm haha

**Comment by trigaten** [comment]
What! `100*100/400*56 = 1400`. What answers are you seeing here? If your temperature is high, it could be answering incorrectly with higher probability.

**Comment by mrboombooms** [comment]
Does 100x100/400x56=1400?? I'm confused haha

**Comment by trigaten** [comment]
Yes it does. Where does your confusion come from?

**Comment by trigaten** [comment]
Closing for now. Lmk if you still see a problem.

**Comment by mrboombooms** [comment]
Yes fair point. Sorry I must of been really out of it when doing this. I
apologise.
