### ISSUE TITLE
Add Least to Most Prompting entry

### ISSUE THREAD

**Issue by wesen** [trigaten/Learn_Prompting#255]
**What topic would you be interested in seeing an article/chapter about?**

Least-to-Most Prompting (already in the bibtex file)

**Any additional info you have about it:**

**Comment by trigaten** [comment]
This should likely be its own page in the intermediate section

**Comment by trigaten** [comment]
@wesen I am reading through currently. This will make a really great page!

**Comment by trigaten** [comment]
Any update here?

**Comment by wesen** [comment]
Good you ask, on it. Hopefully that keeps my ADHD accountable.

**Comment by wesen** [comment]
@trigaten up
