### ISSUE TITLE
Highlighting is hard to read in dark mode

### ISSUE THREAD

**Issue by FabianHertwig** [trigaten/Learn_Prompting#280]
In some articles there are highlighted passages in yellow color, e.g. here https://learnprompting.org/docs/applied_prompting/short_response

When switching to dark mode in the top right corner, the font color switches from black to white and then the highlighted section is very hard to read, because it is white text on a yellow background.

I would expect the color of the highlighting to also change in dark mode, eg. to a very dark yellow.

**Comment by trigaten** [comment]
Good point!

**Comment by trigaten** [comment]
This is being worked on
