### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by lllazarrr** [trigaten/Learn_Prompting#281]
Self-Consistency and Generated Knowledge pages of the Intermediate section are unclear. In particular, I don't how to apply those concepts when using ChatGPT.

**Comment by trigaten** [comment]
I agree. I will say they can't be used with ChatGPT since they require the use of programming. However, on the generated knowledge side, you could say `tell me everything you know about x`. Then ask it a question about x.

I will try to work on this soon.

**Comment by trigaten** [comment]
Generated knowledge is better now :)
