### ISSUE TITLE
New Topic Request: hard prompting vs soft prompting

### ISSUE THREAD

**Issue by HasarinduPerera** [trigaten/Learn_Prompting#297]
**What topic would you be interested in seeing an article/chapter about?**

**Any additional info you have about it:**

I just found this paper and thought maybe it will be useful for the learners.
https://arxiv.org/pdf/2302.03668.pdf

**Comment by dr-nefardio3058** [comment]
Hi there, @HasarinduPerera! We wanted to check in and see if the issue you reported earlier has been resolved. If it has, we would greatly appreciate it if you could take a moment to close the issue. It's super easy – just click the "Close Issue" button at the bottom of the issue page.

Keeping the issue tracker clean and tidy is important for the health of our codebase. With fewer issues to manage, we can focus on the ones that need our attention and ensure that our code remains maintainable in the long run. For example, it's easier to identify trends and common issues when there are fewer open issues, which can lead to more efficient bug fixing and better overall code quality.

Thanks so much for your help in keeping our repo organized and contributing! 😄
