### ISSUE TITLE
What is Dyno imbed?

### ISSUE THREAD

**Issue by yoopr** [trigaten/Learn_Prompting#304]
What is Dyno imbed?

**Comment by yoopr** [comment]
While reading the Basics of your course "learning Prompting" you use a link called Dyno imbed, this part of the course is for "people with little to no experience with prompt engineering or even AI. The target audience here is everyone from non-technical business students to non-technical adults. We will cover the basics of AI, and why you should care about prompt engineering." I am new to all of this and trying to grasp the concepts.
Thanks

**Comment by trigaten** [comment]
Its an interactive tool for testing prompts: https://embed.trydyno.com/
