### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by pleasurecooker** [trigaten/Learn_Prompting#305]
**Sorry, what can I clarify?**
![image](https://user-images.githubusercontent.com/125556966/219338900-91174cd3-066d-427b-b429-0d4f49ccca5e.png)

 Both seems the same, with the same amount of zeros. Please help to clarify, thanks.

**Comment by trigaten** [comment]
The difference is the additional words. `Make sure...`. This creates a different prompt.
