### ISSUE TITLE
Math example

### ISSUE THREAD

**Issue by Atomickvn** [trigaten/Learn_Prompting#335]
In the topic: Role Prompting, there is an example of math solve:

You are a brilliant mathematician who can solve any problem in the world.
Attempt to solve the following problem:

What is 100*100/400*56?

The answer is 1400.

But, when I put it on chatgpt the answer is:

The given expression is:

100 * 100 / 400 * 56

To solve this expression, we follow the order of operations, which is commonly remembered as PEMDAS (Parentheses, Exponents, Multiplication and Division, Addition and Subtraction) or BODMAS (Brackets, Orders, Division and Multiplication, Addition and Subtraction).

Using this order of operations, we perform the multiplication and division operations first, starting from left to right:

= (100 * 100) / (400 * 56)

= 10000 / 22400

We can simplify this fraction by dividing the numerator and denominator by their greatest common factor, which is 400:

= 25 / 56

Therefore, 100100/40056 is equal to 25/56 or approximately 0.4464.

**Comment by trigaten** [comment]
chatgpt is getting it wrong :)

I will link this to a new issue requesting a live embed demo at this location.

<img width="722" alt="Screen Shot 2023-02-21 at 2 32 23 PM" src="https://user-images.githubusercontent.com/42948753/220441037-e4ced669-d2ab-44c0-aa73-963674c2202a.png">
