### ISSUE TITLE
The first wxample

### ISSUE THREAD

**Issue by SrPrie7o** [trigaten/Learn_Prompting#346]
I really don't see the difference on this paragraph  

![image](https://user-images.githubusercontent.com/93624726/221066279-c41e5c80-09bc-42cb-a322-9629c142aabe.png)

**Comment by cr2007** [comment]
Was going to post an issue on the same thing.
I have never been more confused in my life 🗿

**Comment by cr2007** [comment]
Same as #326

**Comment by Mhinoverse** [comment]
It looks like the primary difference between the two prompts is the explicit instructions that come after, in the second prompt.

In Prompt 1: "What is 1,000,000 * 9,000?"
The AI might return an incorrect response (9,000,000) by ignoring the extra zeros from 9000.

But if you are explicit and say to include all zeros, AI has a higher probability of returning the correct answer.
Prompt 2: "What is 1,000,000 * 9,000? Make sure to put the right amount of zeros, even if there are many"

another way a user can word this is like this: "Another way to word Prompt 2 is like this:
"Ensure that the right amount of zeros, even if there are many.  What is 1,000,000 * 9,000?""

**Comment by trigaten** [comment]
Indeed, you are correct @Mhinoverse 

I hope to clarify this soon.
