### ISSUE TITLE
Dyno interactive embed in Example 1 on the Giving Instructions page is requesting an OpenAI API Key...

### ISSUE THREAD

**Issue by adamlemisch** [trigaten/Learn_Prompting#372]
Hello,

I apologize if I am misunderstanding the functionality in the Dyno interactive embed in the first example on the Giving Instructions page but when I attempt to press the "Generate" button I am presented with the following message:
"To modify this example, you'll need to provide your [OpenAI API key](https://beta.openai.com/account/api-keys)"

Screenshot:
<img width="1289" alt="Screenshot 2023-02-28 at 9 00 20 PM" src="https://user-images.githubusercontent.com/3834021/222041827-c85dd217-1046-463d-a43d-258c4c555a47.png">

Or, is obtaining an OpenAI API Key required for this course?

I am using the Brave browser on a mac book air.

Please let me know if I can provide more details. 

Again, I apologize if I am missing something painfully obvious.

Adam

**Comment by trigaten** [comment]
Hello Adam, you will need to provide your OpenAI key. I will add a note on the site to make this clearer.
