### ISSUE TITLE
你是一个优秀的数据家，帮我计算一下100*100/400*56 等于多少

### ISSUE THREAD

**Issue by shexiaobin** [trigaten/Learn_Prompting#408]
**Sorry, what can I clarify?**
<img width="659" alt="image" src="https://user-images.githubusercontent.com/26622879/223016102-d166f0be-1a88-42e1-9986-03e4df820561.png">

**Comment by trigaten** [comment]
ChatGPT is getting it wrong!

> Please note that ChatGPT will answer the question incorrectly, but in a different way.
