### ISSUE TITLE
Clarification - giving instructions api

### ISSUE THREAD

**Issue by haseo101** [trigaten/Learn_Prompting#414]
**Sorry, what can I clarify?**
on the giving instructions page, when you hit generate in the demo, it asks for an API key - as a complete newb i have no idea what this is and the demo doesnt function properly. 

![image](https://user-images.githubusercontent.com/127183737/223348667-696608fe-7dd4-48cc-97f9-1992722b0599.png)

**Comment by trigaten** [comment]
Click on the underlined OpenAI API key text. Basically, you need a 'code' from OpenAI in order to use the demo since it costs money. Ill try to add a page to make this more clear.

**Comment by dr-nefardio3058** [comment]
Is this solved? If it is the case, @haseo101 ,please close this issue as it has been adressed. :)

**Comment by trigaten** [comment]
See this page: https://learnprompting.org/docs/basics/intro#dyno-embeds
