### ISSUE TITLE
How can I use self-consistency?

### ISSUE THREAD

**Issue by woshitoutouge** [trigaten/Learn_Prompting#418]
**Sorry, what can I clarify?**
I am very confused about self-consistency. I understand the explanation in this section, but I don't know how to apply it in ChatGPT

**Comment by trigaten** [comment]
You cannot, unless you are performing API calls

**Comment by dr-nefardio3058** [comment]
Please close this issue as it has been adressed.

**Comment by woshitoutouge** [comment]
sorry i forgot that
