### ISSUE TITLE
Website Feature -- Can I work on a way to mark a chapter as read?

### ISSUE THREAD

**Issue by gangradem** [trigaten/Learn_Prompting#430]
**What feature should we add?**

I like to see my progress as I go through a course.

I'm a web developer. Can I work on this feature, or would this not be ideal for this course?

I suggest a button at the bottom of the page to mark a page as read. I store this page's ID in local storage. Then, show a checkmark next to chapter names when marked as read.

**Comment by trigaten** [comment]
This would be freaking awesome :)

**Comment by trigaten** [comment]
Ideally this could hook into people's Google accounts so they could see progress from other devices (we could store progress data on AWS perhaps)

**Comment by gangradem** [comment]
A bare minimum system could be a basic JS script that stores stuff in LocalStorage. This one should be the fastest to build...

**Comment by gangradem** [comment]
Hey @trigaten, I got busy with some client work and didn't get time for this. I'll get to this tomorrow.

**Comment by trigaten** [comment]
> Hey @trigaten, I got busy with some client work and didn't get time for this. I'll get to this tomorrow.

How is this going?
