### ISSUE TITLE
Clarification in https://learnprompting.org/fr/docs/basic_applications/coding_assistance page_ Python is not mentionned

### ISSUE THREAD

**Issue by El-Doro** [trigaten/Learn_Prompting#446]
Hello,
I was reading this page and it seems that all basic coding examples are written using Python, whereas in the list of coding languages at the top of the page Python is not mentioned in any category.

Could you please add Python to the list for consistency ?
Thank you

**Comment by trigaten** [comment]
Haha, will do

**Comment by dr-nefardio3058** [comment]
Please close this issue as it has been adressed.

**Comment by El-Doro** [comment]
Fixed
