### ISSUE TITLE
language availability

### ISSUE THREAD

**Issue by lbanda01** [trigaten/Learn_Prompting#455]
Only the first 6 topics (almost the complete chapter 1) are available in Spanish, then all of the others are only in English...

**Comment by dr-nefardio3058** [comment]
We're working on it.

**Comment by ABBEN4** [comment]
How can I work on the French version ?

**Comment by dr-nefardio3058** [comment]
> How can I work on the French version ?

Clone repo to your local machine, look for a untranslated file in french (almost every file isn't translated to french), duplicate it to de i18n/fr and start translating. Then open a pull request for your changes to be merge, and try to add a description for providing more details to the owner, for increased probability to get merged. Lets go, and thanks for your wanting to contribute! We highly apreciate you. 😄

**Comment by ABBEN4** [comment]
Great, it's actually faster on Github online directly. I'm also going to look at how to parse the acticles and extract a technical article from them. Does it work the same way? Make an article, submit it somewhere (where?) and comit it?

**Comment by trigaten** [comment]
@ABBEN4 read https://learnprompting.org/contribute#3-translation

**Comment by trigaten** [comment]
@lbanda01 Translation is an ongoing effort :)
