### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Kaman612** [trigaten/Learn_Prompting#460]
<img width="877" alt="截屏2023-03-25 15 03 52" src="https://user-images.githubusercontent.com/128888243/227702731-f0c7df03-bf69-4cd4-a812-eaa24cabdede.png">
wrong output here

**Comment by dr-nefardio3058** [comment]
Hi Kaman! What's the problem here?

**Comment by Kaman612** [comment]
just want to tell output and prompt are not match

**Comment by trigaten** [comment]
Thank you, this was a big oversight.
