### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Mechague1979** [trigaten/Learn_Prompting#484]
**Sorry, where's the typo?** En la parte de Rol Prompt, no le estan indicando a la AI que "Asegúrese de que su respuesta sea exactamente correcta 2 veces" como mencionan en el articulo.

Eres un brillante matemático que puede resolver cualquier problema del mundo.
Intenta resolver el siguiente problema:

¿Cuál es 100*100/400*56?

Ejemplo: ¿A**segúrese de que su respuesta sea exactamente correcta** Cuál es 100*100/400*56 **Asegúrese de que su respuesta sea exactamente correcta** ?

La respuesta es 1400.

**Comment by trigaten** [comment]
I don't see how this is a problem. Role prompting is unrelated to the Asegúrese de que su respuesta sea exactamente correcta 2 veces" example. Could you clarify what is confusing?
