### ISSUE TITLE
New Tool Request - PTPT

### ISSUE THREAD

**Issue by LeslieLeung** [trigaten/Learn_Prompting#507]
https://github.com/LeslieLeung/PTPT

PTPT is an command-line tool that allows you to easily convert plain text files using pre-defined prompts with the help of ChatGPT. With PTPT, you can effortlessly create and share prompt formats, making collaboration and customization a breeze. Plus, by subscribing, you gain access to even more prompts to enhance your experience. If you're interested in prompt engineering, you can use PTPT to develop and share your prompts.

It's similar to OpenPrompt but it purpose a better way of creating, sharing, managing and subscribing prompts.

**Comment by trigaten** [comment]
Would be great if you can PR this in. If not, I will eventually get around to it :)
