### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by BjjRobert** [trigaten/Learn_Prompting#509]
![Screenshot 2023-03-31 at 03-02-47 🟡 Least to Most Prompting Learn Prompting](https://user-images.githubusercontent.com/129182448/228996921-f240b303-6b69-428c-aa41-7814fb09fa6a.png)

Orthography:  ''... wiith 12 words''

**Comment by dr-nefardio3058** [comment]
Fixed in #530

**Comment by BjjRobert** [comment]
![Screenshot 2023-04-01 at 01-43-26 🟢 Solve Discussion Questions Learn Prompting](https://user-images.githubusercontent.com/129182448/229250919-9b2361af-801c-4f6f-8655-9864c2f50464.png)

Orthography: ''Agree our Disagree and why?"

**Comment by dr-nefardio3058** [comment]
> ![Screenshot 2023-04-01 at 01-43-26 🟢 Solve Discussion Questions Learn Prompting](https://user-images.githubusercontent.com/129182448/229250919-9b2361af-801c-4f6f-8655-9864c2f50464.png)
> 
> Orthography: ''Agree our Disagree and why?"

Will fix. Do other issue if u can.

**Comment by dr-nefardio3058** [comment]
Hmu if u find more typos. It's a pleasure to help you and contribute to this project.

**Comment by dr-nefardio3058** [comment]
Fixed in #534
