### ISSUE TITLE
"Misc" section not highlighted in outline in "Contributing" file

### ISSUE THREAD

**Issue by dr-nefardio3058** [trigaten/Learn_Prompting#529]
**In the "Contributing" file of this project, the outline on the right side of the screen does not highlight the "Misc" section. This issue occurs because the text for the "Misc" section is placed next to the footer of the page. To address this issue, I recommend adding some text below the "Misc" section, such as a contact link, to ensure that the "Misc" section is highlighted in the outline when users scroll over it.**

Having a functional outline for a page is essential for many reasons. First, it allows users to navigate the page more efficiently and locate the information they need quickly. Second, it provides a clear and organized structure for the content on the page, which can improve readability and comprehension. Finally, a well-designed outline can enhance the overall user experience and make the page more appealing to visitors.

By highlighting the "Misc" section in the outline, users will have better visibility of this section and will be able to access it more easily. This will ensure that important information contained in the "Misc" section is not overlooked. Additionally, it will improve the overall organization and structure of the "Contributing" file, making it more user-friendly and efficient.

_Demonstration:_

https://user-images.githubusercontent.com/124001513/229200368-518b9d55-b970-4ddc-b4f0-0c4cda91694c.mp4

>Cya! 🐱

**Comment by trigaten** [comment]
Will not fix :) 

This is not a big deal IMO
