### ISSUE TITLE
https://www.jailbreakchat.com

### ISSUE THREAD

**Issue by trigaten** [trigaten/Learn_Prompting#531]

**Comment by dr-nefardio3058** [comment]
Hi men. I'd suggest you to put descriptions to your issues (i know these are you personal notes but still), cause this looks bad and as a contributor, I dont understand it.

Would be cool if you made a standarized issue description (this issue... tries to...) so it's more organized; and contributors, or even I, can help you adressing the issue.

Look it from the perspective of a watcher/contributor: whats https://www.jailbreakchat.com #531? A descriptive issue can be more apealling to contributors and improve quality of the repo. Thanks for your time!
