### ISSUE TITLE
change page lanuage, show "page not found"

### ISSUE THREAD

**Issue by nelson714** [trigaten/Learn_Prompting#572]
installed on m1 macbook air, all page looks great, the only issue is when switch from english to other language. for example like http://localhost:3000/zh-Hans/doc/intro

the page will show "Page not found"

it's happened on all language tag.  
![image](https://user-images.githubusercontent.com/116707917/229659548-5c487c20-f0c7-4c48-85cb-77cd022a3cec.png)

**Comment by trigaten** [comment]
Fortunately the live site work fine. This is odd.

**Comment by trigaten** [comment]
Read this: https://docusaurus.io/docs/i18n/tutorial#start-your-site

This is just part of docusaurus it seems

**Comment by Zakirzhan** [comment]
you should run `npm run build`
after will work
