### ISSUE TITLE
Dyno embeding bug

### ISSUE THREAD

**Issue by jesseangelis** [trigaten/Learn_Prompting#577]
#### Description
Dyno embedding does not work properly. In the first lecture Basics-Introduction I followed the steps as described. However, changing the prompt did not generate a new output. After refreshing the page, the embedding was not visible anymore. Tested on Firefox 111.0.1 (64-bit). JavaScript enabled.

#### Screenshots
![05_04_23_NoNewOutput](https://user-images.githubusercontent.com/72972897/230018023-6bd99bed-9104-4001-adab-7e2382b6b2a9.png)
![05_04_23_MissingEmbedding](https://user-images.githubusercontent.com/72972897/230018057-f9cefd4c-bf8c-481f-b0c7-3c8c9a349319.png)

#### To Reproduce
Delete Cookies and website-data 
Open the lecture Basics-Introduction
Change prompt in dyno embedding
Click "Generate"
Enter API key
Click "Save"
Click "Generate" again --> Output did not change
Refresh page --> Embedding flashes once but remains not visible afterward. Inspecting the HTML shows Error: "Failed to load Dyno Embed: JavaScript must be enabled"
Click the Introduction Tab --> Same Result
Click the Basics Tab
Click the Introduction Tile --> Embedding is visible again.

**Comment by JustinGardiner** [comment]
Dyno embeds aren't working for me either, and I'm on 111.0.5563.147 (Official Build) (64-bit) (cohort: Stable)

**Comment by trigaten** [comment]
Added new embeds
