### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kevinweejh** [trigaten/Learn_Prompting#627]
**Sorry, where's the typo?**
In the 'Basics' chapter, under the 'Giving Instructions' topic, directly below the Dyno embed of Example 1. [https://learnprompting.org/docs/basics/instructions]

"The AI is easily able to solve this problem. We can also ask it ~~can~~ _to_ solve many other simple and more complex problems."

**Comment by pyoneerC** [comment]
fixed in #632
