### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by sd-xu** [trigaten/Learn_Prompting#629]
About [the LLM settings](https://learnprompting.org/docs/basics/configuration_hyperparameters#how-these-hyperparameters-affect-the-output), does a **low top p** value improve **accuracy** and factual correctness?
Isn't the higher the p-value, the model will output words that make up more of the probability mass.

**Comment by trigaten** [comment]
This might be helpful: https://community.openai.com/t/a-better-explanation-of-top-p/2426/8

Lowering it improves accuracy, since it decreases randomness.
