### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by OrionRandD** [trigaten/Learn_Prompting#638]
**Sorry, where's the typo?**

[Step 1: Generate Algabraic Template](https://learnprompting.org/docs/reliability/math#step-1-generate-algabraic-template)
[Step 2: Math Prompts](https://learnprompting.org/docs/reliability/math#step-2-math-prompts)
[2a: Algebraic Statement](https://learnprompting.org/docs/reliability/math#2a-algebraic-statement)
[2b: Python Code](https://learnprompting.org/docs/reliability/math#2b-python-code)
[Answer Generation](https://learnprompting.org/docs/reliability/math#answer-generation)
[Step 4: Self-Consistency](https://learnprompting.org/docs/reliability/math#step-4-self-consistency)
[Conclusion](https://learnprompting.org/docs/reliability/math#conclusion)

Algabraic (in Step1) or Algebraic? In the subtitle. I think I saw it in another two other places...

**Comment by pyoneerC** [comment]
Fixed in #643 lemme know if there are more typos :)
