### ISSUE TITLE
Link to MathGPT in example

### ISSUE THREAD

**Issue by napoles-uach** [trigaten/Learn_Prompting#688]
I there, I'm the creator of MathGPT ([mathgpt.streamlit.app](https://mathgpt.streamlit.app/)) that it is mentioned in the Code Injection Example (https://learnprompting.org/docs/prompt_hacking/offensive_measures/code_injection). It is a personal project that has had an unexpected large attention, which is great! When I released the app in Dec 22 I was not thinking that so much people would test the project, and security was indeed low. Thanks to Ludwig-Ferdinand Stumpp I was warned that some actions must be implemented, and now the app is more secure. I'm happy that you have included it as an example, but could you add the link to the app which is this:

https://mathgpt.streamlit.app/

It would be nice too if you invite the people to not try prompt injecting on it, as every API call has a cost.

Thanks in advance!

**Comment by trigaten** [comment]
Certainly, thank you for reaching out. I will add that note about not injecting :). I am following up over email about a related project that I am working on.

**Comment by napoles-uach** [comment]
Nice! Thanks!
