### ISSUE TITLE
embed Issue on Learn Prompting curse

### ISSUE THREAD

**Issue by ridiaz1** [trigaten/Learn_Prompting#689]
I added the API but now when i want to run an embed, after hitting Generate i get the message"Failed to generate
Unexpected error. Check console for more information.:

**Comment by ridiaz1** [comment]
<img width="1470" alt="Screenshot 2023-05-01 at 09 33 09" src="https://user-images.githubusercontent.com/132281824/235475251-f60a794f-037a-421a-b4db-07ac67956570.png">

**Comment by trigaten** [comment]
We have had multiple reports of this. Here is the embed codebase: https://github.com/PromptLabs/embed.learnprompting.org

We are currently not sure what is causing the problem--the investigation is ongoing.

**Comment by trigaten** [comment]
Have you put your credit card information into your OpenAI account?

**Comment by ridiaz1** [comment]
is it necessary?

**Comment by trigaten** [comment]
> is it necessary?

Yes, you need credits or a credit card attached to your OpenAI account.
I have just updated the embed code to prevent user agent warnings, but I currently believe the main error is coming from not having credits.

**Comment by Philidorable** [comment]
I'm having the same problem.  I just attached a CC today and it still doesn't work, maybe there is a delay propagating the CC info?

**Comment by trigaten** [comment]
Resolving in favor of the clarification issue

**Comment by Philidorable** [comment]
Thanks guys, I went back to it a few weeks ago and for some reason it worked.  Not sure what I did (if anything) but its all good now.
