### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by OSITOPOLAROIT** [trigaten/Learn_Prompting#691]
**Sorry, what can I clarify?**
Mi nombre es Oscar Ivan Torres ‎<ositopolaroit@gmail.com>, pagué mi suscripción a CODEGPT y cada vez que en Visual Studio Code le hago una pregunta a CODGPT me sale este mensaje:
OpenAI API Response was: Error 400: This model's maximum context length is 4097 tokens. However, you requested 10057 tokens (57 in the messages, 10000 in the completion). Please reduce the length of the messages or completion. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors
![image](https://user-images.githubusercontent.com/126188196/235713640-ef6655df-d056-4c02-b90a-9bd06a76036e.png)
![image](https://user-images.githubusercontent.com/126188196/235713685-ea95a768-98e8-495c-9030-500fbd6ee747.png)

**Comment by trigaten** [comment]
We neither own nor operate this plugin, but I sent this to the person who does.

However, a quick look suggests that you are putting in too much text for the model to process.
