### ISSUE TITLE
Integrate repository with a Translation Management System

### ISSUE THREAD

**Issue by silopolis** [trigaten/Learn_Prompting#693]
Hi there,

As a French translator, I'd like to join the team.

Also, if welcome, I'd be willing to integrate the repository with a Translation Management System to bring the project all the goodness of these tools in helping the translators and project maintainers.

I would propose myself to do this, and Crowdin as the chosen TMS because it is an Open-Source friendly platform with a great support team, native Markdown support and integrated ChatGPT.

This would provide a very user-friendly tool for translators, as well as a management tool for translation teams, and a two-way integrated workflow for source and translation files updates, based on GitHub actions.

We should be able to import existing translations, and it would make adding new languages a snap, as the community expands.

Hope yall like the idea

TY
J

**Comment by hayschan** [comment]
A TMS would be great as there are more and more languages in this website. Can't wait to see the addition of the TMS. I am also ready for doing the translation for Cantonese.

**Comment by andrii-bodnar** [comment]
Hi everyone, I'd suggest using [Crowdin GitHub Action](https://github.com/crowdin/github-action) or the [native GitHub integration](https://support.crowdin.com/github-integration/) to automate your localization process 🙂

**Comment by trigaten** [comment]
We are very interested in this, @silopolis please do this! :)

**Comment by Andrulko** [comment]
Hey! Do you need any assistance to configure everything? One team is preparing to localize docs into Ukrainian these days, they will use Crowdin and preliminary, translations would go to the forked repository. I'm helping 'em with configuration, shortly configuration file that you can use for our GitHub connector or GHA would be available here:
https://github.com/Andrulko/Learn_Prompting/blob/main/crowdin.yml

**Comment by trigaten** [comment]
I am currently looking into setting this up

**Comment by trigaten** [comment]
<img width="438" alt="Screen Shot 2023-07-01 at 2 59 04 PM" src="https://github.com/trigaten/Learn_Prompting/assets/42948753/181cb611-8f28-4300-ac23-145086e78924">

/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/%original_file_name%


Currently figuring out how to make the translation path respect the folder structure of the docs (e.g. Images, reliability, etc.)

**Comment by trigaten** [comment]
Here is the link: https://crowdin.com/project/learnprompting/invite?h=0b55419bac9554e1a8233ef64b8791f41753197

**Comment by Andrulko** [comment]
Do you need any further assistance with configuration? Your configuration is quite big, I hope it covers all files
