### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Shahrani00** [trigaten/Learn_Prompting#694]
I’m student in Learn Prompting and I use my iPhone for studying. I’ve been asked to get an [OpenAI API key] from OpenAI to allow me generate text in the embeds.

My questions :-
1- What alternative can I use since OpenAI isn’t available in my country?

2- Since I’m not Developer what type of free API I shall look for ?

Thanks

**Comment by trigaten** [comment]
We dont currently support alternatives, but we are working on it.
