### ISSUE TITLE
Clarification of formulas in Calibration

### ISSUE THREAD

**Issue by ianb** [trigaten/Learn_Prompting#70]
In [this page](https://learnprompting.org/docs/reliability/calibration#technical-solution) there are a number of formulas given, but it could really use some examples to further clarify those formulas.

Some examples:
* Given a 0.9/0.1 distribution for "neutral", what will 0.95 or 0.5 be mapped to?
  * There's two proposed equations, both of which map 0.9/0.1 to 0.5/0.5, but I'm guessing they'll map other values differently
* Because this is specifically mapping two number to two different numbers, can the two equations be mapped to simpler equations?
* A better example than "N/A" would be nice. text-davinci-003 insists the sentiment is also N/A (which is correct, but makes for a poor demonstration)
* I'm not clear how to get those probabilities from GPT-3.

I tried using "full spectrum" probabilities in the GPT-3 playground in order to see its probabilities, but I get this and I'm not sure how to map it to this calibration:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/44390/206284288-0ec5e7c7-f15c-42e3-8dc0-21b6387d741c.png">

**Comment by trigaten** [comment]
>  they'll map other values differently
yep
> can the two equations be mapped to simpler equations?
Exactly what 2 equations are your referring to?

Noted on the rest of these points. I am not sure how to get the probs from GPT3 atm either.

**Comment by ianb** [comment]
> > can the two equations be mapped to simpler equations?
> 
> Exactly what 2 equations are your referring to?

They aren't given a name, but I think these are effectively two equations:

1. W=diag( pˆ) **−1

2. b could also be set to -p, and W to the identity matrix

**Comment by trigaten** [comment]
Resolving this in https://github.com/trigaten/Learn_Prompting/pull/78

Please let me know if this is not sufficient :)
