### ISSUE TITLE
Clarification at blog_gegeration page

### ISSUE THREAD

**Issue by ndNovaDev** [trigaten/Learn_Prompting#700]
**Sorry, what can I clarify?**
Can not understand "here are many products which attempt to do this, but you can often get consistent results doing it yourself. " at [https://learnprompting.org/docs/basic_applications/blog_generation](url)

**Comment by trigaten** [comment]
There are many blog generation products, but you can often make a good blog using ChatGPT without these other products.

**Comment by ndNovaDev** [comment]
> There are many blog generation products, but you can often make a good blog using ChatGPT without these other products.

So the issue may be that this sentence is in the wrong place, making people think that it is part of the prompt

**Comment by trigaten** [comment]
I will refine the text before closing this issue :)

**Comment by trigaten** [comment]
Yep you were completely right :)
