### ISSUE TITLE
Prompt Instruction for Coding Assistance Missing "#" Symbol

### ISSUE THREAD

**Issue by ndNovaDev** [trigaten/Learn_Prompting#701]
**Sorry, where's the typo?**
The documentation on https://learnprompting.org/docs/basic_applications/coding_assistance#commenting-and-reformatting-code mentions that after the prompt instruction, three hashmarks should be added before pasting in the code for clean-up. However, the prompt provided below does not include the hashmarks, potentially causing confusion for readers.

**Comment by pyoneerC** [comment]
Duplicate #665
