### ISSUE TITLE
New Product Request

### ISSUE THREAD

**Issue by sohrabhosseini** [trigaten/Learn_Prompting#722]
**What product should we add?**

Orquesta AI Prompts: https://orquesta.cloud/platform/ai-llm-prompts

No-code collaboration platform for AI Prompts
- Full prompt lifecycle management (from ideation to feedback collection)
- Enterprise-grade features and security
- Support for public, private, and custom LLMs
- Prompts based on custom context and business rules. Evaluations on the Edge
- Real-time logging and collection of performance and prompt economics

**Comment by trigaten** [comment]
Please make a PR :)

**Comment by trigaten** [comment]
Thanks for the report @sohrabhosseini! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @sohrabhosseini! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @sohrabhosseini! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @sohrabhosseini! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @sohrabhosseini! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @sohrabhosseini! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @sohrabhosseini! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @sohrabhosseini! I will look into it ASAP! (I'm an experimental bot).
