### ISSUE TITLE
Clarification: Java not referenced 

### ISSUE THREAD

**Issue by jowitte** [trigaten/Learn_Prompting#727]
No Java mentioned on docs/basic_applications/coding_assistance.md - although GPT itself references it.

![image](https://github.com/trigaten/Learn_Prompting/assets/8180200/b0143ddc-6552-4672-91f3-ee6d0f5e237d)

**Comment by trigaten** [comment]
Thanks for the report @jowitte! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @jowitte! I will look into it ASAP! (I'm an experimental bot).
