### ISSUE TITLE
Setting API key on the back-end / in embed settings

### ISSUE THREAD

**Issue by dadaismee** [trigaten/Learn_Prompting#735]
Hello! 

I would like to use (your gorgeous) embeds in my project. However, they require users to input their own API keys, and this might affect UX. Is it possible to set a once-and-for-all API key on my side (e.g. my API key with pro account) so that the users of my project will not be bothered with creating their own API keys? Maybe, it is possible somehow in embed settings?

**Comment by trigaten** [comment]
You can see the source here: https://github.com/PromptLabs/embed.learnprompting.org

You could adapt it to support your use case.
