### ISSUE TITLE
Source/reference for why you think Role Prompting is no longer effective in modern AIs?

### ISSUE THREAD

**Issue by zyrain** [trigaten/Learn_Prompting#752]
The Note makes this claim, but there's nothing I can find in the literature to back it up.

**Comment by trigaten** [comment]
Good question, I am still looking for references. That note is currently anecdotal (but strongly so).

**Comment by hiteshbandhu** [comment]
I have one link i just read, maybe it can help a little bit.

https://hbr.org/2023/06/ai-prompt-engineering-isnt-the-future

**Comment by trigaten** [comment]
> I have one link i just read, maybe it can help a little bit.
> 
> https://hbr.org/2023/06/ai-prompt-engineering-isnt-the-future

What part of the article supports this?

**Comment by trigaten** [comment]
I put that it is anecdotal--I don't think that information on this currently exists, it would be an interesting area of research!
