### ISSUE TITLE
Clarification: Authorship according to the American Psychological Association, 7th edition

### ISSUE THREAD

**Issue by seonghobae** [trigaten/Learn_Prompting#756]
**Sorry, what can I clarify?**

Hi, I'm a psychologist and work on an AI development team. I'm trying to cite this article and there's one odd thing I'm noticing.
As far as I know from my training and years of studying psychology, the 7th edition of the American Psychological Association rules prohibit mixing "individual" and "collective" in authorship, meaning you can't use an individual's name with a collective of contributors, so after "Schulhoff, Sander" you have to list all the contributors in alphabetical order, or use a collective name like "Learn Prompting Workgroup".
So I'm a bit stuck on how to cite this document, and I'm hoping you can help.

Thanks.

Best regards, 
Seongho Bae

**Comment by trigaten** [comment]
Interesting, go ahead and just use just "Schulhoff, Sander" or also add "Learn Prompting Workgroup", whichever is easier.
