### ISSUE TITLE
basic_applications/coding_assistance page: Dyno embeding bug

### ISSUE THREAD

**Issue by Evanavevan** [trigaten/Learn_Prompting#765]
There is a Dyno embeding bug in basic_applications/coding_assistance page:
![image](https://github.com/trigaten/Learn_Prompting/assets/44725772/4e2075f7-d4ee-4fed-887d-b3d6d55d205f)

**Comment by trigaten** [comment]
Seems to have been resolved

**Comment by Evanavevan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你发的邮件我已经收到，我会尽快阅读你的邮件的
