### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Smok3onthewater** [trigaten/Learn_Prompting#781]
**Sorry, where's the typo?**
In Basics>Prompting>2) Math Word Problem Solving, we read:

**_For a given question, your full prompt could look like this:

What is 965*590?

For this prompt, GPT-3 (text-davinci-003) (an AI) sometimes answers 569,050 (incorrect). This is where prompt engineering comes in._**

569,050 is correct for 965*590. What GPT returns is 568,050 and that is incorrect.

**Comment by trigaten** [comment]
Thanks for the report @Smok3onthewater! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @Smok3onthewater! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
<img width="219" alt="Screen Shot 2023-07-10 at 2 49 41 AM" src="https://github.com/trigaten/Learn_Prompting/assets/42948753/97f1d72f-b3d3-499b-9507-0e792ad2a1c9">

Seems you are missing the 3. GPTs will return different answers.
