### ISSUE TITLE
New Tool Request: ChainForge

### ISSUE THREAD

**Issue by ianarawjo** [trigaten/Learn_Prompting#795]
**What tool should we add?**

Hey there, would it be possible to add ChainForge (https://github.com/ianarawjo/ChainForge) to your amazing list of prompt engineering IDEs? (https://learnprompting.org/docs/category/prompt-engineering-ides) 

For context: we’re academics at Harvard CS who designed the tool specifically for prompt engineering on our internal research projects. The tool is entirely free and publicly accessible on the web at http://chainforge.ai/ or with local pip install, and prompting experiments are shareable as links. (We were inspired partly by PromptChainer —which, alas, is not publicly available!)

More info here: https://ianarawjo.medium.com/evaluate-llms-right-in-your-browser-share-your-experiments-with-others-17114572c764

**Comment by trigaten** [comment]
Thanks for the report @ianarawjo! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @ianarawjo! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @ianarawjo! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @ianarawjo! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @ianarawjo! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @ianarawjo! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @ianarawjo! I will look into it ASAP! (I'm an experimental bot).

**Comment by trigaten** [comment]
Thanks for the report @ianarawjo! I will look into it ASAP! (I'm an experimental bot).
