### ISSUE TITLE
Translating into Indonesian Language [Page: Welcome]

### ISSUE THREAD

**Issue by arnoldapg** [trigaten/Learn_Prompting#863]
# Selamat Datang

Selamat datang di kursus pengantar teknik prompt engineering!

Prompt engineering (PE) adalah proses **mengkomunikasikan secara efektif dengan AI untuk mencapai hasil yang diinginkan**. Seiring dengan pesatnya kemajuan teknologi AI, kemampuan menguasai teknik prompt engineering menjadi suatu keterampilan yang sangat berharga. Teknik prompt engineering dapat diterapkan pada berbagai hal, sehingga menjadi alat yang berguna bagi siapa saja yang ingin meningkatkan efisiensi dalam aktivitas sehari-hari maupun aktivitas yang bersifat inovatif.

Kursus ini disesuaikan untuk **pemula**, sehingga menjadi titik awal yang sempurna bagi Anda yang baru dalam bidang AI dan PE. Namun, bahkan jika Anda bukan pemula, Anda masih akan menemukan wawasan yang berharga dalam kursus ini. Kursus ini adalah kursus prompt engineering yang **paling komprehensif**, dan konten yang disajikan mulai dari pengenalan tentang AI hingga teknik PE yang paling mutakhir.

## Etos dan Filosofi

Kursus ini bersifat open source, dan dibangun oleh komunitas yang beragam, terdiri dari peneliti, penerjemah, dan hobi. Kami percaya bahwa AI harus dapat diakses oleh semua orang, dan harus dideskripsikan secara jelas dan objektif. Oleh karena itu, kami berusaha untuk menghasilkan kursus yang komprehensif dan tidak bias yang bebas dari jargon dan hype yang berlebihan.

Kami melihat bahwa pendekatan ini diminati oleh komunitas PE: Kursus ini dikutip oleh [Wikipedia](https://en.wikipedia.org/wiki/Prompt_engineering#cite_ref-15), dan digunakan oleh orang-orang di perusahaan seperti [O'REILLY](https://learning.oreilly.com/live-events/prompt-engineering-for-generating-ai-art-and-text/0636920084340/0636920084339/), Scale AI, dan OpenAI. Anda juga mungkin melihat bahwa [hampir](https://youtu.be/GPqSoiOP3w8?t=274) [setiap](https://learnwithhasan.com/prompt-engineering-guide/) [video](https://www.youtube.com/watch?v=EYjG6i53-xk) [dan](https://youtu.be/yR4hNBNS6yc?t=743) [panduan](https://youtu.be/pZsJbYIFCCw?t=208) [prompt](https://youtu.be/4kp7oVTu9Ck?t=495) [engineering](https://www.youtube.com/watch?v=q5wuHUmGFMw) [lainnya](https://youtu.be/f8PGV3T9w38?t=549) menggunakan materi dari kursus ini. Kami merasa terhormat dapat mendukung komunitas prompt engineering, termasuk 620 ribu pengguna dan 33 ribu anggota [Discord](https://discord.gg/learn-prompting).

### Bagaimana Kami Mengajarkan

Pendekatan kami dalam mengajar prompt engineering dipandu oleh prinsip-prinsip berikut:

**Iterasi Cepat**—Karena konten PE diterbitkan hampir setiap hari, kami akan menjaga agar kursus ini tetap terbaru dengan artikel-artikel yang singkat dan sering update tentang teknik-teknik yang baru muncul. Beri tahu kami topik apa yang ingin Anda jelajahi lebih lanjut!

**Penekanan pada Kepraktisan**—Fokus kami adalah pada teknik-teknik terapan dan praktis yang dapat Anda terapkan secara langsung pada proyek dan aplikasi Anda.

**Contoh yang Mudah Dipahami**—Untuk membantu Anda mengerti teknik-teknik tersebut dengan cepat, kami akan menyediakan contoh yang jelas dan relevan di seluruh artikel.

**Pembelajaran Kolaboratif**—Kami percaya dalam belajar dari satu sama lain. Jika Anda menemukan sesuatu yang kurang dipahami atau menemukan kesalahan, silakan beri tahu kami dengan membuat issue di GitHub. Umpan balik Anda membantu kami meningkatkan kursus untuk semua orang.

> CATATAN
Kursus ini sedang dalam pengembangan yang besar. Kami bekerja keras untuk meningkatkan pengalaman belajar dan menambah lebih banyak konten. Jika Anda memiliki saran, silakan beritahu kami!
> 

## Cara Membaca

Tidak perlu membaca semua bab secara berurutan; Anda bebas untuk menjelajahi apa yang menarik bagi Anda! Jika Anda baru dalam AI, machine learning, dan pemrograman, kami menyarankan untuk memulai dengan bagian [Dasar](https://learnprompting.org/docs/category/-basics) dan panduan [Instruksi](https://learnprompting.org/docs/basics/intro). Bagi mereka yang sudah familiar dengan konsep-konsep ini, bagian [Menengah](https://learnprompting.org/docs/category/%EF%B8%8F-intermediate) adalah tempat yang tepat untuk memperluas pengetahuan Anda.

### Sistem Rating Artikel

Kami telah menerapkan sistem rating artikel berdasarkan tingkat kesulitan dan tingkat keahlian pemrograman yang diperlukan:

🟢 Cocok untuk pemula; tidak diperlukan pemrograman

🟡 Mudah; pengetahuan dasar pemrograman diperlukan, tetapi tidak memerlukan keahlian khusus

🔴 Menengah; keterampilan pemrograman dan sedikit pengetahuan domain diperlukan (misalnya, menghitung probabilitas logaritmik)

🟣 Lanjutan; keahlian pemrograman dan pemahaman domain yang mendalam diperlukan (misalnya, teknik reinforcement learning)

Harap dicatat bahwa bahkan untuk artikel 🔴 dan 🟣, Anda umumnya dapat memahami konten tanpa keahlian sebelumnya, meskipun mungkin perlu implementasi.

### Bab

Di bawah ini adalah gambaran singkat tentang setiap bab:

**Dasar-dasar**: Pengenalan tentang prompt engineering dan teknik-teknik dasar

**Aplikasi Dasar**: Aplikasi praktis dan sederhana dari prompt engineering

**Menengah**: Teknik-teknik PE berbasis penelitian dengan kompleksitas sedang

**Prompting Terapan**: Proses PE yang komprehensif yang dikontribusikan oleh anggota komunitas

**Aplikasi Lanjutan**: Aplikasi prompt engineering yang lebih kuat dan kompleks

**Keandalan**: Meningkatkan keandalan large language models (LLM)

**Gambar**: Prompt engineering untuk model teks-ke-gambar, seperti DALLE dan Stable Diffusion

**Prompt Injection**: Hacking, tetapi untuk prompt engineering

**Peralatan**: Tinjauan tentang berbagai alat dan IDE prompt engineering

**Penyetelan Prompt**: Memperhalus prompt menggunakan teknik berbasis gradien

**Miscellaneous**: Koleksi topik dan teknik tambahan terkait prompt engineering

## Umpan Balik

Bagian terpenting dari kursus ini adalah umpan balik Anda!

Jika Anda memiliki pertanyaan, komentar, atau saran, Anda dapat:

- Buat [issue di GitHub](https://github.com/trigaten/Learn_Prompting/issues/new/choose)
- Kirim email ke [learnprompting@gmail.com](mailto:learnprompting@gmail.com)
- Bergabung dengan [komunitas Discord](https://learnprompting.org/discord)
- Ikuti kami di [Twitter](https://twitter.com/learnprompting)
- Bergabung dengan Kompetisi HackAPrompt hingga 26 Mei [(Twitter)
](https://www.aicrowd.com/challenges/hackaprompt-2023)

Bahkan sedikit umpan balik sangat membantu!

**Comment by trigaten** [comment]
Being done through crowding
